apiVersion: v1
kind: Service
metadata: 
  name: svc-pod-1
spec: 
  type: NodePort
  ports:
    - port: 80
      #targetPort: 80 não precisa definir se for igual ao port
      nodePort: 30000
      #30000 até 32767
  selector: 
    app: primeiro-pod