apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: ngnix-pod
      labels:
        app: ngnix-pod-label
    spec:
        containers:
          - name: ngnix-container
            image: nginx:1
            ports:
              - containerPort: 80
  selector:
    matchLabels:
      app: ngnix-pod-label

